// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package main

import (
	"github.com/Disaxy/fast-track/tasks"
	"github.com/google/uuid"
	mock "github.com/stretchr/testify/mock"
)

// NewMockTaskStorage creates a new instance of MockTaskStorage. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockTaskStorage(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockTaskStorage {
	mock := &MockTaskStorage{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockTaskStorage is an autogenerated mock type for the TaskStorage type
type MockTaskStorage struct {
	mock.Mock
}

type MockTaskStorage_Expecter struct {
	mock *mock.Mock
}

func (_m *MockTaskStorage) EXPECT() *MockTaskStorage_Expecter {
	return &MockTaskStorage_Expecter{mock: &_m.Mock}
}

// AddTask provides a mock function for the type MockTaskStorage
func (_mock *MockTaskStorage) AddTask(task *main.Task) error {
	ret := _mock.Called(task)

	if len(ret) == 0 {
		panic("no return value specified for AddTask")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(*main.Task) error); ok {
		r0 = returnFunc(task)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockTaskStorage_AddTask_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddTask'
type MockTaskStorage_AddTask_Call struct {
	*mock.Call
}

// AddTask is a helper method to define mock.On call
//   - task *main.Task
func (_e *MockTaskStorage_Expecter) AddTask(task interface{}) *MockTaskStorage_AddTask_Call {
	return &MockTaskStorage_AddTask_Call{Call: _e.mock.On("AddTask", task)}
}

func (_c *MockTaskStorage_AddTask_Call) Run(run func(task *main.Task)) *MockTaskStorage_AddTask_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *main.Task
		if args[0] != nil {
			arg0 = args[0].(*main.Task)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockTaskStorage_AddTask_Call) Return(err error) *MockTaskStorage_AddTask_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockTaskStorage_AddTask_Call) RunAndReturn(run func(task *main.Task) error) *MockTaskStorage_AddTask_Call {
	_c.Call.Return(run)
	return _c
}

// GetTask provides a mock function for the type MockTaskStorage
func (_mock *MockTaskStorage) GetTask(id uuid.UUID) (*main.Task, error) {
	ret := _mock.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for GetTask")
	}

	var r0 *main.Task
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(uuid.UUID) (*main.Task, error)); ok {
		return returnFunc(id)
	}
	if returnFunc, ok := ret.Get(0).(func(uuid.UUID) *main.Task); ok {
		r0 = returnFunc(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*main.Task)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(uuid.UUID) error); ok {
		r1 = returnFunc(id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTaskStorage_GetTask_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetTask'
type MockTaskStorage_GetTask_Call struct {
	*mock.Call
}

// GetTask is a helper method to define mock.On call
//   - id uuid.UUID
func (_e *MockTaskStorage_Expecter) GetTask(id interface{}) *MockTaskStorage_GetTask_Call {
	return &MockTaskStorage_GetTask_Call{Call: _e.mock.On("GetTask", id)}
}

func (_c *MockTaskStorage_GetTask_Call) Run(run func(id uuid.UUID)) *MockTaskStorage_GetTask_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 uuid.UUID
		if args[0] != nil {
			arg0 = args[0].(uuid.UUID)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockTaskStorage_GetTask_Call) Return(task *main.Task, err error) *MockTaskStorage_GetTask_Call {
	_c.Call.Return(task, err)
	return _c
}

func (_c *MockTaskStorage_GetTask_Call) RunAndReturn(run func(id uuid.UUID) (*main.Task, error)) *MockTaskStorage_GetTask_Call {
	_c.Call.Return(run)
	return _c
}

// RemoveTask provides a mock function for the type MockTaskStorage
func (_mock *MockTaskStorage) RemoveTask(id uuid.UUID) error {
	ret := _mock.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for RemoveTask")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(uuid.UUID) error); ok {
		r0 = returnFunc(id)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockTaskStorage_RemoveTask_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RemoveTask'
type MockTaskStorage_RemoveTask_Call struct {
	*mock.Call
}

// RemoveTask is a helper method to define mock.On call
//   - id uuid.UUID
func (_e *MockTaskStorage_Expecter) RemoveTask(id interface{}) *MockTaskStorage_RemoveTask_Call {
	return &MockTaskStorage_RemoveTask_Call{Call: _e.mock.On("RemoveTask", id)}
}

func (_c *MockTaskStorage_RemoveTask_Call) Run(run func(id uuid.UUID)) *MockTaskStorage_RemoveTask_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 uuid.UUID
		if args[0] != nil {
			arg0 = args[0].(uuid.UUID)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockTaskStorage_RemoveTask_Call) Return(err error) *MockTaskStorage_RemoveTask_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockTaskStorage_RemoveTask_Call) RunAndReturn(run func(id uuid.UUID) error) *MockTaskStorage_RemoveTask_Call {
	_c.Call.Return(run)
	return _c
}
